# Generated by Django 4.2 on 2023-04-20 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_profile_access_token_profile_expires_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('instance_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('Kin', 'Kinetic'), ('En', 'Energy'), ('Hev', 'Heavy')], default='Kin', max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('instance_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('H', 'Kinetic'), ('A', 'Arms'), ('Ch', 'Chest'), ('L', 'Legs'), ('Cl', 'Class')], default='H', max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
