# Generated by Django 4.2 on 2023-04-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_delete_armor_delete_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.IntegerField()),
                ('total_minutes', models.IntegerField()),
                ('session_minutes', models.IntegerField()),
                ('last_played', models.DateField()),
                ('emblem_icon', models.CharField(max_length=500)),
                ('emblem_background', models.CharField(max_length=500)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.class')),
                ('race_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.race')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
