# Generated by Django 4.2 on 2023-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_class_race_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_played',
            field=models.CharField(max_length=255),
        ),
    ]
