# Generated by Django 4.2 on 2023-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_profile_destiny2_membership_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='destiny2_membership_id',
            field=models.CharField(default='pizza', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_type',
            field=models.CharField(max_length=500),
        ),
    ]
